services:
  app:
    build: app
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build: api
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: