services:
  app:
    build: app
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    depends_on:
      - api

  api:
    build: api
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql
  
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080

volumes:
  mariadb_data: