services:
  app:
    image: node:22 # ghcr.io/devcontainers/templates/typescript-node:22
    ports:
      - "4200:4200"
    volumes:
      - ./app:/workspace/app
    working_dir: /workspace/app
    command: ["npm", "start"]
    depends_on:
      - api

  api:
    image: eclipse-temurin:24 # ghcr.io/devcontainers/templates/java:24-jdk
    ports:
      - "8080:8080"
    volumes:
      - ./api:/workspace/api
    working_dir: /workspace/api
    command: "./mvnw spring-boot:run"
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql
  
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080

volumes:
  mariadb_data: