services:
  app:
    image: node:22
    volumes:
      - ./app:/workspace/app
    working_dir: /workspace/app
    command: sleep infinity
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    image: eclipse-temurin:24
    volumes:
      - ./api:/workspace/api
    working_dir: /workspace/api
    command: sleep infinity
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql
  
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080

volumes:
  mariadb_data: