services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    command: sleep infinity

  api:
    image: mcr.microsoft.com/devcontainers/java:21-bookworm
    depends_on:
      - db
    command: sleep infinity

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frigo
      MYSQL_USER: frigo
      MYSQL_PASSWORD: frigo
    volumes:
      - mariadb_data:/var/lib/mysql
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 81:8080
    depends_on:
      - db

  idp:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8888:8080
    environment:
      KC_HOSTNAME: http://localhost:8888
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./idp/frigo-realm.json:/opt/keycloak/data/import/frigo-realm.json:ro
    command: start-dev --import-realm

volumes:
  mariadb_data: