name: API Package

on:
  release:
    types: [created]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: api

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: frigo-api-jar
          path: target

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
