name: Api Deploy

concurrency: frigo-api

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/api-build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: frigo-api

    steps:        
      - name: Download frigo-app artifact
        uses: actions/download-artifact@v4
        with:
          name: frigo-api
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: frigo-api

      - name: frigo-api version
        run: ls frigo.api-* | sed 's/.*-\([0-9].*\)\.jar$/\1/'
        env:
          FRIGO_API_VERSION: ls frigo.api-* | sed 's/.*-\([0-9].*\)\.jar$/\1/'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: ${{ FRIGO_API_VERSION }}
          version_description: ${{github.SHA}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: frigo.api-*.jar

