name: API Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/api-build.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: frigo-api
      
      - name: List downloaded files
        run: ls -la
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publish to GitHub Packages Apache Maven
        working-directory: api
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
