name: App Deploy

concurrency: frigo-app

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/app-build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: frigo-app

    steps:        
      - name: Download frigo-app artifact
        uses: actions/download-artifact@v4
        with:
          name: frigo-app
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: frigo-app
        
      - name: Deploy to AWS S3
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: frigo-app
          destination_dir: .
