name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: node-app-build-${{ matrix.node-version }}
        path: app/dist
        retention-days: 7
